// Programmer: Rueil Manzambi
// MST Username: rnm8cm
// Instructor: Johnathan Dunker
// Section: 301
// Date: 02/09/2021
// File: lab4.cpp
// Description: This program plays a game where the user has four shots to guess a random number between 11 and 21 inclusive

#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;


int main()
{
  // variable declaration and initialization
  int user_choice = 1; // initialized to 1 to enter the while loop
  int rand_number; // generated by the computer
  int user_attempt; // user's guess
  int shot_number; // user's shots (has a total of 4 to guess the right number)

  srand(time(0)); // seeds the random number generator
  // Header
  cout << "\t\t\tWelcome to the Guess Game"<< endl;

  while (user_choice != 3) // execute until the user quits (option 3)
  {
    do // prompts the user to enter only 1, 2 or 3
    {
      cout << "(1) Enter 1 to see the game rules."<< endl;
      cout << "(2) Enter 2 to play the game."<< endl;
      cout << "(3) Enter 3 to quit the game."<< endl;
      cout << "Enter your choice:"<< endl;
      cin >> user_choice;
      if (user_choice < 1 || user_choice > 3)
        cout << "Invalid choice. Your choice must be 1, 2, or 3."<< endl;
    } while (user_choice < 1 || user_choice > 3);

    switch (user_choice) // continue the program following user's choice of option
    {
      case 1: // to see the rules
        cout <<"############################# GAME RULES ###############################"<< endl;
        cout <<"You have to guess a number between 11 to 20 inclusive."<< endl;
        cout <<"You have got 4 shots to guess it right and win the game."<< endl;
        cout <<"###################################################################"<< endl;
        break;
      case 2: // to play the game
        rand_number = rand() % (21 - 11) + 11; // finds random number between 11 and 20 inclusive
        for (shot_number = 1; shot_number <= 4; shot_number++)
        {
          cout << "Guess a number between 11 to 20 inclusive."<< endl;
          cout << "Attempt No "<< shot_number <<": ";
          cin >> user_attempt;
          if (user_attempt == rand_number) // user's attempt is corrects, he wins 
          {
            cout << "Congratulations! You have won the guess game!!"<< endl;
            shot_number = 5; // sets to five so the loop won't execute again
          }
          if (shot_number == 4 && user_attempt != rand_number) // if user's attempt is incorrect and it's the last possible shot, the user loses the game
          {
            cout << "You loose! Better luck next time."<< endl;  
          }
        }    
        break;
      case 3: // to quit 
        cout <<"Thanks for playing the guess game! The game will now quit...."<< endl;
        break;
    }
  } 
  return 0;
}
